stages:
  - docs

before_script:
  - mkdir ~/.ssh
#  - echo $GITHUB_DEPLOY_KEY_PAGES >> ~/.ssh/id_rsa
#  - chmod 400 ~/.ssh/id_rsa
  - ssh-add <(echo "$GITHUB_DEPLOY_KEY_PAGES")
  - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
#  - git config --global user.email "pasta@pizza.italia"
#  - git config --global user.name "Gitlab CI Pipeline"

documentation:
  stage: docs
  image: python:3.8.5-buster
  script:
    - pip install pdoc3
    - pip install -r requirements.txt
    - git clone git@github.com:flopana/teamspeak3-server-updater.github.io.git
    - pdoc --html ../teamspeak3-server-updater
    - mv html/teamspeak3-server-updater teamspeak3-server-updater.github.io/
    - cd teamspeak3-server-updater.github.io
    - git add .
    - git commit -m "docs"
    - git push