stages:
  - docs

before_script:
  - mkdir ~/.ssh
  - echo $GITHUB_DEPLOY_KEY_PAGES >> ~/.ssh/id_rsa

documentation:
  stage: docs
  image: python:3.8.5-buster
  script:
    - pip install pdoc3
    - pip install -r requirements.txt
    - git clone https://github.com/flopana/teamspeak3-server-updater.github.io
    - pdoc --html ../teamspeak3-server-updater
    - mv html/teamspeak3-server-updater teamspeak3-server-updater.github.io/
    - cd teamspeak3-server-updater.github.io
    - git add .
    - git commit -m "docs"